### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by Cangit** [bluedaniel/Kakapo-native#3] opened 2016-02-10 11:19 UTC
OSX 10.11.4
Kakapo 1.2 downloaded from the website today.
Happens on every launch.

Screenshot of error msg
![screen shot 2016-02-10 at 12 16 24](https://cloud.githubusercontent.com/assets/1426157/12945852/8cf686ee-cff0-11e5-8ac9-cfe54f33e050.png)

**Comment by bluedaniel** [comment] 2016-02-11 20:32
Hi Cangit, thanks for reporting the crash.

It's caused by malformed JSON in the user-data folder. It's fixed in the
latest code but I've not pushed n update yet.

Version 1.3 will be coming out soon

**Comment by bluedaniel** [comment] 2016-03-30 08:45
I've fixed this issue on the latest Desktop release. I will be focusing my efforts on refactoring the code for Native starting today. Thanks for your patience!

**Closed as completed** 2016-04-09 15:02 UTC
